[package]
name = "purrmint"
version = "0.1.0"
edition = "2021"
authors = ["PurrMint Developers"]
description = "High-level Cashu NIP-74 mint service suitable for Android (via JNI)"
license = "MIT"
repository = "https://github.com/purrmint/purrmint"
keywords = ["cashu", "nostr", "nip74", "mint", "lightning"]
categories = ["api-bindings", "cryptography", "network-programming"]

[lib]
name = "purrmint"
crate-type = ["cdylib", "staticlib", "rlib"]

[build-dependencies]
cbindgen = "0.24"

[dependencies]
# Async runtime
tokio = { version = "1", features = ["rt-multi-thread", "macros", "signal"] }
async-trait = "0.1"
tracing = "0.1"

nostr = { path = "../nostr/crates/nostr", features = ["std", "nip44"] }
nostr-sdk = { path = "../nostr/crates/nostr-sdk", features = ["all-nips"] }
nostr-connect = { path = "../nostr/crates/nostr-connect" }

cdk = { path = "../cdk/crates/cdk" }
cdk-sqlite = { path = "../cdk/crates/cdk-sqlite" }
cdk-fake-wallet = { path = "../cdk/crates/cdk-fake-wallet" }

serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "2"
sha2 = "0.10"
base32 = "0.4"
reqwest = { version = "0.11", features = ["json", "rustls-tls"], default-features = false }

# Logging
tracing-subscriber = { version = "0.3", features = ["fmt", "env-filter"] }

rand = "0.8"
uuid = { version = "1" }
once_cell = "1.21.3"
jni = { version = "0.21", optional = true }

[features]
# Feature to build JNI bindings later
jni-support = ["jni"] 
